services:
  # Web Application (nginx serving static files)
  aps-web:
    image: nginx:alpine
    container_name: aps-healthcare-web
    ports:
      - "3000:80"
    volumes:
      - ./src/Web/APS.WebApp/wwwroot:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - postgresql
      - redis
      - rabbitmq
    networks:
      - aps-network
    restart: unless-stopped

  # Base de dados PostgreSQL
  postgresql:
    image: postgres:15-alpine
    container_name: aps-postgresql
    environment:
      - POSTGRES_DB=aps_saude
      - POSTGRES_USER=aps
      - POSTGRES_PASSWORD=aps123
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aps -d aps_saude"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aps-network
    restart: unless-stopped

  # Cache Redis
  redis:
    image: redis:7-alpine
    container_name: aps-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass aps123
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aps-network
    restart: unless-stopped

  # Message Broker RabbitMQ
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: aps-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=aps
      - RABBITMQ_DEFAULT_PASS=aps123
      - RABBITMQ_DEFAULT_VHOST=aps_vhost
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - aps-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local

networks:
  aps-network:
    driver: bridge